//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uyegirisuygulama.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Kullanicilar
    {
        public int Kul_ID { get; set; }
        [Required(ErrorMessage="Lütfen Kullanici Adi Giriniz",AllowEmptyStrings=false)]
        public string Kul_AD { get; set; }
        [Required(ErrorMessage="Lütfen Parolanizi Giriniz",AllowEmptyStrings=false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Kul_PAROLA { get; set; }
    }
}
